
/*
special areas:
start: a
silver key: g
gold key: D
slot machine: E
RPG points: F
final block: !
*/

const AREAS_GRID = [
'abbggoosssssKJJHHHHG',
'cccggpppxyyLKJJNIFFG',
'deehmmrttyyMMJJNIFFG',
'dffhmmrttyyMMJJOOOOO',
'ijjhqqqqzyyMMPPOOOOO',
'ijjhqqqqzQQQQDDSSSRR',
'knnnuAAAzQQQQDDSSSRR',
'knnnuAAAzWWXXXXVVURR',
'kvvwuCBBzWWXXXXVVURR',
'kvvwuCBBzTTTTTTTTTTT',
'lvv33CBBz%%@@YY88ZZ1',
'l4433C$$$$$@@YY99ZZ1',
'l5533^^----@@YY99001',
'66633^^----@@EE]]]]1',
'666&&^^)))(@@EE||[[1',
'666&&^^)))(___=++[[1',
'77777****#(___=++222',
'!!!!!!!!!!!!!!!!!!!!',
'!!!!!!!!!!!!!!!!!!!!',
'!!!!!!!!!!!!!!!!!!!!'
];

const AREAS = [
  { sym: '!', type: 'cell', val: 1e308 },
  { sym: 'a', type: 'spawn', val: 10 },
  { sym: 'b', type: 'cell', val: 10 },
  { sym: 'c', type: 'cell', val: 10 },
  { sym: 'd', type: 'cell', val: 10 },
  { sym: 'e', type: 'cell', val: 10, lock: 1 },
  { sym: 'f', type: 'cell', val: 10, lock: 1 },
  { sym: 'g', type: 'keys', val: 10 },
  { sym: 'h', type: 'cell', val: 10, lock: 1 },
  { sym: 'i', type: 'cell', val: 10, lock: 1 },
  { sym: 'j', type: 'cell', val: 10 },
  { sym: 'k', type: 'cell', val: 10 },
  { sym: 'l', type: 'cell', val: 10 },
  { sym: 'm', type: 'cell', val: 10 },
  { sym: 'n', type: 'cell', val: 10 },
  { sym: 'o', type: 'cell', val: 10 },
  { sym: 'p', type: 'cell', val: 10, lock: 1 },
  { sym: 'q', type: 'cell', val: 10 },
  { sym: 'r', type: 'cell', val: 10, lock: 1 },
  { sym: 's', type: 'cell', val: 10, lock: 1 },
  { sym: 't', type: 'cell', val: 10 },
  { sym: 'u', type: 'cell', val: 10, lock: 1 },
  { sym: 'v', type: 'cell', val: 10, lock: 1 },
  { sym: 'w', type: 'cell', val: 10 },
  { sym: 'x', type: 'cell', val: 10 },
  { sym: 'y', type: 'cell', val: 10, lock: 1 },
  { sym: 'z', type: 'cell', val: 10, lock: 1 },
  { sym: 'A', type: 'cell', val: 10, lock: 1 },
  { sym: 'B', type: 'cell', val: 10 },
  { sym: 'C', type: 'cell', val: 10, lock: 2 },
  { sym: 'D', type: 'keyg', val: 10 },
  { sym: 'E', type: 'slot', val: 10 },
  { sym: 'F', type: 'rpgp', val: 10 },
  { sym: 'G', type: 'cell', val: 10, lock: 1 },
  { sym: 'H', type: 'cell', val: 10, lock: 1 },
  { sym: 'I', type: 'cell', val: 10, lock: 1 },
  { sym: 'J', type: 'cell', val: 10 },
  { sym: 'K', type: 'cell', val: 10 },
  { sym: 'L', type: 'cell', val: 10, lock: 1 },
  { sym: 'M', type: 'cell', val: 10 },
  { sym: 'N', type: 'cell', val: 10 },
  { sym: 'O', type: 'cell', val: 10, lock: 1 },
  { sym: 'P', type: 'cell', val: 10, lock: 1 },
  { sym: 'Q', type: 'cell', val: 10, lock: 1 },
  { sym: 'R', type: 'cell', val: 10, lock: 2 },
  { sym: 'S', type: 'cell', val: 10 },
  { sym: 'T', type: 'cell', val: 10, lock: 2 },
  { sym: 'U', type: 'cell', val: 10 },
  { sym: 'V', type: 'cell', val: 10, lock: 2 },
  { sym: 'W', type: 'cell', val: 10 },
  { sym: 'X', type: 'cell', val: 10, lock: 1 },
  { sym: 'Y', type: 'cell', val: 10, lock: 2 },
  { sym: 'Z', type: 'cell', val: 10, lock: 2 },
  { sym: '1', type: 'cell', val: 10 },
  { sym: '2', type: 'cell', val: 10 },
  { sym: '3', type: 'cell', val: 10, lock: 2 },
  { sym: '4', type: 'cell', val: 10, lock: 2 },
  { sym: '5', type: 'cell', val: 10 },
  { sym: '6', type: 'cell', val: 10 },
  { sym: '7', type: 'cell', val: 10, lock: 2 },
  { sym: '8', type: 'cell', val: 10 },
  { sym: '9', type: 'cell', val: 10 },
  { sym: '0', type: 'cell', val: 10 },
  { sym: '@', type: 'cell', val: 10, lock: 2 },
  { sym: '#', type: 'cell', val: 10, lock: 2 },
  { sym: '$', type: 'cell', val: 10 },
  { sym: '%', type: 'cell', val: 10 },
  { sym: '^', type: 'cell', val: 10, lock: 2 },
  { sym: '&', type: 'cell', val: 10 },
  { sym: '*', type: 'cell', val: 10, lock: 2 },
  { sym: '(', type: 'cell', val: 10, lock: 2 },
  { sym: ')', type: 'cell', val: 10 },
  { sym: '-', type: 'cell', val: 10 },
  { sym: '_', type: 'cell', val: 10, lock: 2 },
  { sym: '=', type: 'cell', val: 10, lock: 2 },
  { sym: '+', type: 'cell', val: 10, lock: 2 },
  { sym: '[', type: 'cell', val: 10 },
  { sym: ']', type: 'cell', val: 10, lock: 2 },
  { sym: '|', type: 'cell', val: 10 },
];

const AREAS_ORDER = 'abcedfjhinqmpvwouxrsAtyQLKJNHMGPIORUVST%$8Z0kl-Y149]@XWzBC3^*56&)[|7#2+=(_!';
const AREAS_NAMES = "fire,youth,spear,tag,blade,team,drake,aide,lord,slope,depot,cacao,dart,cash,enemy,corn,chalk,brace,vodka,pit,beet,pay,group,usher,lad,bark,means,toot,owl,noun,pecan,query,belt,chip,tower,plow,lyre,cone,fate,feast,equal,envy,crop,giant,inbox,feel,stalk,yoga,down,eaves,color,guess,hit,epoxy,mix,stick,rider,cube,nuke,shop,class,prow,prior,flat,spine,fob,gun,wrap,manor,ore,right,inn,verb,swamp,cot,pain,fish,bead,tour,wheat,price,taco,yoyo,pupa,slash,song,pole,kitty,jeep,dump,deed,match,novel,bake,spell,toy,dozen,start,crate,lava,sand,perch,birch,oil,purse,uncle,cow,mass,leek,perp,snack,boar,fawn,seal,scene,wok,orchid,sheet,top,shore,tap,radar,text,prose,hire,ear,chap,drama,syrup,mud,kazoo,past,age,body,share,west,dog,treat,habit,wharf,wit,tenet,bread,depth,wave,whale,talk,fig,asset,turf,shed,lag,trout,upper,aside,craw,beach,glass,tale,finer,canal,blog,topic,loaf,kale,gold,info,claw,storm,need,hop,chaos,genre,tweet,lark,hide,maple,cap,chin,yam,wind,louse,aim,back,adobe,gown,smog,spud,dwell,floor,dune,grace,goat,owner,grill,front,aid,sash,tuber,pyramid,frost,icing,bulk,hill,venom,wine,clank,towel,skin,lieu,fold,meat,boot,level,derby,wheel,brood,short,bend,brand,jump,grin,cycle,bun,scope,wear,hold,glue,latte,stone,math,coat,purr,raft,pun,white,bug,wrong,wreck,slide,sprag,guava,torte,dryer,canoe,hobby,curl,yolk,fill,hope,slaw,mover,month,dip,coil,drive,light,chasm,pearl,pig,mango,media,drain,tune,madam,taste,dime,blast,paint,gnat,spot,roar,sail,film,panda,sill,dance,ham,pimp,pizza,hunt,kilt,tempo,bet,wifi,grain,net,rug,actor,hint,crow,brick,cub,mint,spite,potty,lily,glen,humor,snow,leaf,ferry,lipid,pad,pen,wild,yard,final,pupil,bath,waist,kite,elver,link,opera,unity,cello,clamp,wage,dare,put,grey,stand,troop,hound,merit,bride,thump,air,movie,puma,arrow,fund,bidet,row,poker,break,eye,heir,park,sonar,birth,cross,glee,hose,sense,niece,lane,cabin,monk,lace,fairy,quest,puppy,king,pond,bird,chill,fail,attic,foray,claim,proof,bail,bayou,pork,seed,basin,jack,print,hug,tub,hub,graft,liver,vest,lung,gem,donut,sari,patty,event,chord,wish,poem,stop,squid,oboe,fruit,show,bunch,sushi,mound,twist,south,meal,food,fiber,mark,wood".split(',');
