
/*
special areas:
start: a
silver key: g
gold key: D
slot machine: E
RPG points: F
final block: !
*/

const AREAS_GRID = [
'abbggoosssssKJJHHHHG',
'cccggpppxyyLKJJNIFFG',
'deehmmrttyyMMJJNIFFG',
'dffhmmrttyyMMJJOOOOO',
'ijjhqqqqzyyMMPPOOOOO',
'ijjhqqqqzQQQQDDSSSRR',
'knnnuAAAzQQQQDDSSSRR',
'knnnuAAAzWWXXXXVVURR',
'kvvwuCBBzWWXXXXVVURR',
'kvvwuCBBzTTTTTTTTTTT',
'lvv33CBBz%%@@YY88ZZ1',
'l4433C$$$$$@@YY99ZZ1',
'l5533^^----@@YY99001',
'66633^^----@@EE]]]]1',
'666&&^^)))(@@EE||[[1',
'666&&^^)))(___=++[[1',
'77777****#(___=++222',
'!!!!!!!!!!!!!!!!!!!!',
'!!!!!!!!!!!!!!!!!!!!',
'!!!!!!!!!!!!!!!!!!!!'
];

const AREAS = [
  { sym: '!', type: 'cell', val: 1e308 },
  { sym: 'a', type: 'spawn', val: 10 },
  { sym: 'b', type: 'cell', val: 10 },
  { sym: 'c', type: 'cell', val: 10 },
  { sym: 'd', type: 'cell', val: 10 },
  { sym: 'e', type: 'cell', val: 10 },
  { sym: 'f', type: 'cell', val: 10 },
  { sym: 'g', type: 'keys', val: 10 },
  { sym: 'h', type: 'cell', val: 10 },
  { sym: 'i', type: 'cell', val: 10 },
  { sym: 'j', type: 'cell', val: 10 },
  { sym: 'k', type: 'cell', val: 10 },
  { sym: 'l', type: 'cell', val: 10 },
  { sym: 'm', type: 'cell', val: 10 },
  { sym: 'n', type: 'cell', val: 10 },
  { sym: 'o', type: 'cell', val: 10 },
  { sym: 'p', type: 'cell', val: 10 },
  { sym: 'q', type: 'cell', val: 10 },
  { sym: 'r', type: 'cell', val: 10 },
  { sym: 's', type: 'cell', val: 10 },
  { sym: 't', type: 'cell', val: 10 },
  { sym: 'u', type: 'cell', val: 10 },
  { sym: 'v', type: 'cell', val: 10 },
  { sym: 'w', type: 'cell', val: 10 },
  { sym: 'x', type: 'cell', val: 10 },
  { sym: 'y', type: 'cell', val: 10 },
  { sym: 'z', type: 'cell', val: 10 },
  { sym: 'A', type: 'cell', val: 10 },
  { sym: 'B', type: 'cell', val: 10 },
  { sym: 'C', type: 'cell', val: 10 },
  { sym: 'D', type: 'keyg', val: 10 },
  { sym: 'E', type: 'slot', val: 10 },
  { sym: 'F', type: 'rpgp', val: 10 },
  { sym: 'G', type: 'cell', val: 10 },
  { sym: 'H', type: 'cell', val: 10 },
  { sym: 'I', type: 'cell', val: 10 },
  { sym: 'J', type: 'cell', val: 10 },
  { sym: 'K', type: 'cell', val: 10 },
  { sym: 'L', type: 'cell', val: 10 },
  { sym: 'M', type: 'cell', val: 10 },
  { sym: 'N', type: 'cell', val: 10 },
  { sym: 'O', type: 'cell', val: 10 },
  { sym: 'P', type: 'cell', val: 10 },
  { sym: 'Q', type: 'cell', val: 10 },
  { sym: 'R', type: 'cell', val: 10 },
  { sym: 'S', type: 'cell', val: 10 },
  { sym: 'T', type: 'cell', val: 10 },
  { sym: 'U', type: 'cell', val: 10 },
  { sym: 'V', type: 'cell', val: 10 },
  { sym: 'W', type: 'cell', val: 10 },
  { sym: 'X', type: 'cell', val: 10 },
  { sym: 'Y', type: 'cell', val: 10 },
  { sym: 'Z', type: 'cell', val: 10 },
  { sym: '1', type: 'cell', val: 10 },
  { sym: '2', type: 'cell', val: 10 },
  { sym: '3', type: 'cell', val: 10 },
  { sym: '4', type: 'cell', val: 10 },
  { sym: '5', type: 'cell', val: 10 },
  { sym: '6', type: 'cell', val: 10 },
  { sym: '7', type: 'cell', val: 10 },
  { sym: '8', type: 'cell', val: 10 },
  { sym: '9', type: 'cell', val: 10 },
  { sym: '0', type: 'cell', val: 10 },
  { sym: '@', type: 'cell', val: 10 },
  { sym: '#', type: 'cell', val: 10 },
  { sym: '$', type: 'cell', val: 10 },
  { sym: '%', type: 'cell', val: 10 },
  { sym: '^', type: 'cell', val: 10 },
  { sym: '&', type: 'cell', val: 10 },
  { sym: '*', type: 'cell', val: 10 },
  { sym: '(', type: 'cell', val: 10 },
  { sym: ')', type: 'cell', val: 10 },
  { sym: '-', type: 'cell', val: 10 },
  { sym: '_', type: 'cell', val: 10 },
  { sym: '=', type: 'cell', val: 10 },
  { sym: '+', type: 'cell', val: 10 },
  { sym: '[', type: 'cell', val: 10 },
  { sym: ']', type: 'cell', val: 10 },
  { sym: '|', type: 'cell', val: 10 },
];
